name: .NET

on:
  push:
    branches: [ main ]
    tags:
    - 'v*'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  pipeline:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install WASM
      run: dotnet workload install wasm-tools 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o 'drop' 
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '**/drop/appsettings.json'
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.connectionstring }}
        Email.Password: ${{ secrets.email_password }}
    # Begin Automated Deployment
    - name: Create app_offline file
      shell: pwsh
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
          New-Item app_offline.html -ItemType File
          Set-Content app_offline.html `
          '<html xmlns="http://www.w3.org/1999/xhtml">
          <head>
              <title>
                  Dynamo League - Site Maintenance
              </title>
              <style tyle="text/css">
                  body {
                      text-align: center;
                      padding: 150px;
                  }

                  h1 {
                      font-size: 50px;
                  }

                  body {
                      font: 20px Helvetica, sans-serif;
                      color: #333;
                  }

                  article {
                      display: block;
                      text-align: left;
                      width: 650px;
                      margin: 0 auto;
                  }

                  a {
                      color: #dc8100;
                      text-decoration: none;
                  }

                      a:hover {
                          color: #333;
                          text-decoration: none;
                      }
              </style>
              <meta content="JavaScript" name="vs_defaultClientScript">
              <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
              <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
          </head>
          <body>
              <article>
                  <h1>We&rsquo;ll be back soon!</h1>
                  <div>
                      <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. We&rsquo;ll be back online shortly!</p>
                  </div>
              </article>
          </body>
          </html>'
    - name: Take App Offline
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        server: win5184.site4now.net
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: 'DynamoLeagueBlazor/'
        server-dir: '/'
        exclude: |
          **/drop/**
        dry-run: true
    - name: Deploy to Prod
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        server: win5184.site4now.net
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: 'drop/'
        server-dir: '/'
        dry-run: true
    - name: Bring App Online
      uses: JesseTG/rm@v1.0.0
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        path: app_offline.html
