name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build-publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install WASM
      run: dotnet workload install wasm-tools 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o 'drop' 
    - uses: actions/upload-artifact@v2
      with:
        name: dynamoleague
        path: drop
      
  web-deploy:
    name: Deploy
    runs-on: windows-latest
    needs: [build-publish]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dynamoleague
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: win5184.site4now.net
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: '/'
        server-dir: 'dynamoleague/'
        dry-run: true
